### PR TITLE
Add Slack Webhook documentation

### PR DESCRIPTION
**Pull request by adamzimmermann**
## Description

We should document how to use these features.

### CODE REVIEW

**Review by mmatsoo — APPROVED** [review]
👍 A lovely sentence, to be sure. Any benefit in adding an example URL or clarifying where to get it, so the developer knows what `SLACK_WEBHOOK_URL` should look like?

**Comment by adamzimmermann** [comment]
@mmatsoo good idea. 💡 

@markdorison handled all of that for me, so perhaps he could contribute a line or two to this PR as well.

**Comment by markdorison** [comment]
Updated!

**Comment by adamzimmermann** [comment]
@markdorison thank you! 🏆

**Pull request merged**
